version: "3.9"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - medusa-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6380:6380"

  medusa:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        REDIS_URL: ${REDIS_URL}
        COOKIE_SECRET: ${COOKIE_SECRET}
        JWT_SECRET: ${JWT_SECRET}
        STORE_CORS: ${STORE_CORS}
        ADMIN_CORS: ${ADMIN_CORS}
        AUTH_CORS: ${AUTH_CORS}
        PORT: ${PORT}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    command: ["./entrypoint.sh"]
    restart: unless-stopped

volumes:
  medusa-db-data:
