services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medusa_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - medusa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "medusa_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - medusa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    container_name: medusa-backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-medusa_db}?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      MEDUSA_ADMIN_ONBOARDING_TYPE: ${MEDUSA_ADMIN_ONBOARDING_TYPE:-default}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${BACKEND_PORT:-9000}
      WORKER_MODE: ${WORKER_MODE:-shared}
      NODE_OPTIONS: "--max-old-space-size=3072"
      STORE_CORS: ${STORE_CORS:-http://localhost:3001}
      ADMIN_CORS: ${ADMIN_CORS:-http://localhost:9000}
      AUTH_CORS: ${AUTH_CORS:-http://localhost:9000}
      TS_NODE_TRANSPILE_ONLY: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-9000}:${BACKEND_PORT:-9000}"
    networks:
      - medusa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 180s  # Increased for key creation
    volumes:
      - publishable_key_volume:/app/.env.publishable:ro  # Share key with storefront

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    container_name: medusa-storefront
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: ${PUBLIC_BACKEND_URL:-http://backend:9000}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${STOREFRONT_PORT:-3001}
      NODE_OPTIONS: "--max-old-space-size=2048"
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${STOREFRONT_PORT:-3001}:${STOREFRONT_PORT:-3001}"
    networks:
      - medusa_network
    restart: unless-stopped
    volumes:
      - publishable_key_volume:/app/.env.publishable:ro  # Share key from backend

volumes:
  postgres_data:
    driver: local
  publishable_key_volume:
    driver: local

networks:
  medusa_network:
    driver: bridge