version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa-postgres
    environment:
      POSTGRES_DB: medusa_db
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_secure_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dokploy
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'      # 33% of CPU
          memory: 1G       # 25% of RAM
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medusa_user -d medusa_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    networks:
      - dokploy
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'      # 17% of CPU
          memory: 256M     # 6% of RAM
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: medusa-backend
    environment:
      DATABASE_URL: postgres://medusa_user:medusa_secure_password_123@postgres:5432/medusa_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: GUA6uNfbbl9nksLumoVc0VulzElEEqbqC6zsaYBAF0c=
      COOKIE_SECRET: fvYJhZmUuMRcdjjZi2+OHK+xK0Fqsr9KMA2hLqcqEo8=
      MEDUSA_ADMIN_ONBOARDING_TYPE: default
      NODE_ENV: production
      PORT: 3000
      WORKER_MODE: shared
      # Memory optimization for Node.js
      NODE_OPTIONS: "--max-old-space-size=1536"
      # Temporary CORS - will update after getting real domains
      STORE_CORS: "*"
      ADMIN_CORS: "*"
      AUTH_CORS: "*"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dokploy
    ports:
      - "3000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'      # 33% of CPU (Medusa needs more CPU)
          memory: 1.5G     # 37% of RAM
        reservations:
          cpus: '0.5'
          memory: 768M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend-${COMPOSE_PROJECT_NAME}.traefik.me`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  storefront:
    build: 
      context: ./storefront
      dockerfile: Dockerfile
    container_name: medusa-storefront
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://backend:3000
      NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: pk_placeholder
      NODE_ENV: production
      PORT: 3001
      # Memory optimization for Next.js
      NODE_OPTIONS: "--max-old-space-size=1024"
    depends_on:
      - backend
    networks:
      - dokploy
    ports:
      - "3001:3001"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'      # 17% of CPU
          memory: 1G       # 25% of RAM
        reservations:
          cpus: '0.25'
          memory: 512M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront.rule=Host(`store-${COMPOSE_PROJECT_NAME}.traefik.me`)"
      - "traefik.http.services.storefront.loadbalancer.server.port=3001"

volumes:
  postgres_data:
    driver: local

networks:
  dokploy:
    external: true