services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-medusa_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Must be set in .env or Dokploy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - medusa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "medusa_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - medusa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    container_name: medusa-backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-medusa_db}?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      MEDUSA_ADMIN_ONBOARDING_TYPE: ${MEDUSA_ADMIN_ONBOARDING_TYPE:-default}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${BACKEND_PORT:-9000}
      WORKER_MODE: ${WORKER_MODE:-shared}
      NODE_OPTIONS: "--max-old-space-size=2564"
      STORE_CORS: ${STORE_CORS:-http://localhost:3001}
      ADMIN_CORS: ${ADMIN_CORS:-http://localhost:9000}
      AUTH_CORS: ${AUTH_CORS:-http://localhost:9000}
      TS_NODE_TRANSPILE_ONLY: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-9000}:${BACKEND_PORT:-9000}"
    networks:
      - medusa_network
    restart: unless-stopped
    # NO healthcheck here - using the one from Dockerfile

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    container_name: medusa-storefront
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: ${PUBLIC_BACKEND_URL:-http://backend:9000}
      NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY: ${MEDUSA_PUBLISHABLE_KEY}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${STOREFRONT_PORT:-3001}
      NODE_OPTIONS: "--max-old-space-size=1856"
    depends_on:
      backend:
        condition: service_started
    ports:
      - "${STOREFRONT_PORT:-3001}:${STOREFRONT_PORT:-3001}"
    networks:
      - medusa_network
    restart: unless-stopped
    # NO healthcheck here - using the one from Dockerfile

volumes:
  postgres_data:
    driver: local

networks:
  medusa_network:
    driver: bridge