version: "3.9"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - medusa-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6380:6380"

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        REDIS_URL: redis://redis:6380/0
        WORKER_MODE: server
        COOKIE_SECRET: supersecret
        JWT_SECRET: 4870377b462a73ce988c2d52b713b08b
        STORE_CORS: "*"
        ADMIN_CORS: "*"
        AUTH_CORS: "*"
        PORT: 9000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6380/0
      - WORKER_MODE=server
      - COOKIE_SECRET=supersecret
      - JWT_SECRET=4870377b462a73ce988c2d52b713b08b
      - STORE_CORS=*
      - ADMIN_CORS=*
      - AUTH_CORS=*
      - PORT=9000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    command: ["./entrypoint.sh"]
    restart: unless-stopped

volumes:
  medusa-db-data:
