# nixpacks.toml - Perfekt optimiert für MedusaJS B2B Starter auf CPX21
# Konfiguriert für: 4GB RAM, 3 vCPU, PostgreSQL + Redis

providers = ["node"]

[variables]
# Production-Umgebung
NODE_ENV = "production"
# Node.js 20 LTS für beste Kompatibilität und Performance
NIXPACKS_NODE_VERSION = "20"
# Memory-Optimierung für CPX21 (4GB RAM)
NODE_OPTIONS = "--max-old-space-size=2048"
# NPM-Konfiguration für Production-Builds
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
# Node.js 20 und Yarn installieren
nixPkgs = ["nodejs_20", "yarn"]
# Zusätzliche Tools für bessere Performance
nixLibs = ["openssl"]

[phases.install]
# Corepack aktivieren und Dependencies installieren 
cmds = [
    "cd backend && corepack enable && yarn install --frozen-lockfile --network-timeout 300000"
]
# Cache-Verzeichnisse für Yarn 4 (Modern Yarn)
cacheDirectories = [
    "backend/node_modules",
    "backend/.yarn/cache"
]

[phases.build]
# MedusaJS Backend builden mit Corepack
cmds = [
    "cd backend && corepack enable && yarn medusa build"
]
# Build-Cache für wiederholte Deployments
cacheDirectories = [
    "backend/dist",
    "backend/node_modules/.cache"
]

[start]
# Production-Start mit Corepack und Medusa CLI
# Port 9000 ist der Standard für MedusaJS
cmd = "cd backend && corepack enable && yarn medusa start"